### ISSUE TITLE
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

### ISSUE THREAD

**Issue by vilkenrid** [deforum/stable-diffusion#135]
HI,
I  am new and  cannot find answear for the problem I  got. My animation suddenly  stop with  info:
"NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."
When  I press PLAY in Setup at the beginning of   my deforum_Stable Diffusion  it gives me above info.
Is this relevant  with my low standard plan purchased ?Do I have some daily  limitations? I  have noticed that after  24 hours  it starts working again. Or is this some problem with my  Nvidia Drivers?

**Comment by cynamonster** [comment]
I think I can shed some light on the issue you're facing. Google is giving you free access to their GPUs to run the Colab Notebook. You're likely getting this error because their free-tier GPUs are in high demand and they aren't able to allocate one for you. That's why it works when you try again later.

Options to resolve:
- Purchase premium GPU time from Google Colab, or
- Connect Google Colab to a local runtime, probably with Jupyter Notebook running locally on your machine.
